BEGIN;

ALTER TABLE donations ADD COLUMN IF NOT EXISTS donor_name VARCHAR(160);
ALTER TABLE donations ADD COLUMN IF NOT EXISTS donor_email VARCHAR(320);
ALTER TABLE donations ADD COLUMN IF NOT EXISTS verified_amount_kobo BIGINT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS provider_transaction_id VARCHAR(32);
ALTER TABLE donations ADD COLUMN IF NOT EXISTS payment_channel VARCHAR(64);
ALTER TABLE donations ADD COLUMN IF NOT EXISTS provider_fee_kobo BIGINT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS provider_paid_at TIMESTAMPTZ;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS accounted_at TIMESTAMPTZ;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS thanked BOOLEAN NOT NULL DEFAULT FALSE;

COMMIT;
